export const fakeListingData = [
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
  {
    car: "Aston Martin",
    rating: 5,
    event: "Weddings/Forals",
    user: "Bennybot",
    price: 1200,
  },
];
